# Generated by Django 2.2.14 on 2020-07-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_daefqfcrqrfcqrefc"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="jhfjhfjgfhgfjfgjhjkhg",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
