# Generated by Django 2.2.14 on 2020-07-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_jhfjhfjgfhgfjfgjhjkhg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ggtrfkuytkuytkuyt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jytuytuyt', models.BigIntegerField()),
            ],
        ),
    ]
